import {
  blueFrame,
  butterFrame,
  frame,
  grassFrame,
  greenFrame,
  maxFrame,
  pinkFogFrame,
  pinkFrame,
  tecotalkNoFrame,
  tecotalkYesFrame,
  toastFrame,
  whiteFrame,
  wooteco6Frame,
  wooteco7Frame,
} from '@/assets/frames';

export const frames: Record<string, string> = {
  토스트: toastFrame,
  // 버건디: gdyFrame,
  무한도전: greenFrame,
  초록초록: grassFrame,
  맥스날드: maxFrame,
  y2k핑크: pinkFogFrame,
  // 토스: tossFrame,
  내가우테코6기: wooteco6Frame,
  내가우테코7기: wooteco7Frame,
  테코톡끗: tecotalkYesFrame,
  테코톡아직: tecotalkNoFrame,
  블랙: frame,
  블루베리: blueFrame,
  핑크: pinkFrame,
  버터: butterFrame,
  화이트: whiteFrame,
};
